### ISSUE TITLE
Move the repo to github.com/ceph

### ISSUE THREAD

**Issue by leseb** [Ulexus/docker-ceph#9]
Hello,

Thanks a lot for the work, I've tried both mon and odds for now and it seems to work quite well.

Would you interested (and willing) to move this repo to github.com/docker-ceph?
I truly believe this is the best place for this repo :).
Obviously you will keep all the credits and merge rights on this new repo.

Same goes for your images on Docker hub, I've created a Ceph organisation and can easily add you.
My goal is to provide 'trusted container images' that come from Ceph.

So, interested? :-)

Cheers.

**Comment by Ulexus** [comment]
I would be delighted, yes.  Just add me to the orgs, and I'll transfer the repos over.

**Comment by leseb** [comment]
Hum I don't have the permissions at the moment, can you push a PR first then I'll see what we can do?
No worries you won't lose credits and I'll make sure that you will get admin rights to merge PR.
Thanks!

**Comment by Ulexus** [comment]
Done
